name: Simple Release Builder Fix

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true
        default: 'v2.2.1-LanguageFixed'
        type: string

jobs:
  build-release:
    name: "Build Release"
    runs-on: windows-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: srt_whisper_lite/electron-react-app/package-lock.json

    - name: Install Node Dependencies
      run: |
        cd srt_whisper_lite/electron-react-app
        npm ci

    - name: Build React App
      run: |
        cd srt_whisper_lite/electron-react-app
        npm run react:build

    - name: Build Electron App
      run: |
        cd srt_whisper_lite/electron-react-app
        npm run dist:portable

    - name: Create Release Assets
      run: |
        $version = "${{ github.event.inputs.version }}"
        mkdir release_assets
        
        # Copy portable version if it exists
        if (Test-Path "srt_whisper_lite/electron-react-app/dist/win-unpacked") {
          Compress-Archive -Path "srt_whisper_lite/electron-react-app/dist/win-unpacked/*" -DestinationPath "release_assets/SRT-GO-$version-Portable.zip"
        }
        
        # Copy any installer if it exists
        $installer = Get-ChildItem "srt_whisper_lite/electron-react-app/dist/*.exe" -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($installer) {
          Copy-Item $installer.FullName "release_assets/SRT-GO-$version-Setup.exe"
        }
        
        # List what we created
        Get-ChildItem release_assets

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: SRT GO ${{ github.event.inputs.version }}
        body: |
          # SRT GO Language-Fixed Release
          
          ## Features
          - Complete multi-language support (5 languages)
          - 100% E2E test coverage
          - Advanced voice detection
          - Cross-platform compatibility
          
          ## Installation
          Download the portable version or use the setup installer.
          
          Built with GitHub Actions
        files: release_assets/*
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}